#ifndef MEDICAL_MEDICALDIALECT_H
#define MEDICAL_MEDICALDIALECT_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"

// This is the "Magic" include.
// It includes the declarations generated by TableGen.
#include "Medical/MedicalDialect.h.inc"

#endif // MEDICAL_MEDICALDIALECT_H